Bump version to 2.0.0 app version
opensearch-project/helm-charts pull request #270
Opened 2022-05-23 23:32 UTC by peterzhuamazon

Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

### Description
Bump version to 2.0.0 app version
 
### Issues Resolved
Part of opensearch-project/opensearch-build#2086
 
### Check List
- [x] Commits are signed per the DCO using --signoff

For any changes to files within Helm chart directories:
- [x] Helm chart version bumped
- [x] Helm chart `CHANGELOG.md` updated to reflect change

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/helm-charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-05-23 23:35 UTC, bbarani approved these changes
Don't merge until 2.0 GA version is released.

2022-05-23 23:36 UTC, zelinh approved these changes

2022-05-23 23:37 UTC, zelinh requested changes
Block until 2.0.0 released.

2022-05-26 18:06 UTC, zelinh approved these changes

2022-05-26 18:09 UTC, TheAlgo commented
IMO this should be in draft stage 🙂

2022-05-26 18:36 UTC, merged