template configmap values
opensearch-project/helm-charts pull request #316
Opened 2022-09-01 12:17 UTC by bkomraz1

Signed-off-by: Boris Komraz <bkomraz1@gmail.com>

### Description
[Describe what this change achieves.]
 
### Issues Resolved
[List any issues this PR will resolve. You should likely open an issue if one does not already exist.]
 
### Check List
- [ ] Commits are signed per the DCO using --signoff

For any changes to files within Helm chart directories:
- [ ] Helm chart version bumped
- [ ] Helm chart `CHANGELOG.md` updated to reflect change

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/helm-charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-09-01 13:13 UTC, bkomraz1 commented
Adding @peterzhuamazon

2022-09-02 00:37 UTC, DandyDeveloper requested changes
Looks like the yml `tpl` isn't working. 

![image](https://user-images.githubusercontent.com/18436531/188034587-93c5e7ad-6d53-4481-9815-97f81bed52a4.png)

I think in your defaults you meant `.Values.serverHost`? 


Beyond this, everything looks good. Fix the conflicts, I'll approve!

2022-09-04 08:37 UTC, bkomraz1 commented
> Looks like the yml `tpl` isn't working.
> 
> ![image](https://user-images.githubusercontent.com/18436531/188034587-93c5e7ad-6d53-4481-9815-97f81bed52a4.png)
> 
> I think in your defaults you meant `.Values.serverHost`?
> 
> Beyond this, everything looks good. Fix the conflicts, I'll approve!

I fixed values.yaml:

```
  #  opensearch_dashboards.yml:
  #   server:
  #     name: dashboards
  #     host: "{{ .Values.serverHost }}"
```

```
helm template . | grep        host: -C 5
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/managed-by: Helm
data:
  opensearch_dashboards.yml: |
    server:
      host: '0.0.0.0'
      name: dashboards
---

2022-09-04 23:17 UTC, DandyDeveloper approved these changes
Looks good, the only one recommendation I'd have is perhaps moving this to a function in the `_helpers.tpl` but since these are two different charts. This might actually be more effort then its worth.

LGTM regardless!

2022-09-15 18:39 UTC, peterzhuamazon commented
Sorry for the delay @bkomraz1 adding @prudhvigodithi to take a look.
Thanks.

2022-09-15 18:40 UTC, peterzhuamazon commented on charts/opensearch-dashboards/values.yaml
> +  #     host: "{{ .Values.serverHost }}"
Is it possible to add these changes in README?

2022-09-19 16:09 UTC, prudhvigodithi commented
Hey @bkomraz1 thanks for the PR, the only test I was looking for, does `helm upgrade` with this change breaks for works fine, can you please post your testing here?
Thank you

2022-09-19 20:25 UTC, bkomraz1 commented
```
(⎈ |docker-desktop:default):opensearch$ 
cd opensearch-project-helm-charts/charts/opensearch
helm search repo opensearch
NAME                            	CHART VERSION	APP VERSION	DESCRIPTION
opensearch/opensearch           	2.6.0        	2.3.0      	A Helm chart for OpenSearch
opensearch/opensearch-dashboards	2.5.1        	2.3.0      	A Helm chart for OpenSearch Dashboards
(⎈ |docker-desktop:default):opensearch$ helm install opensearch opensearch/opensearch
NAME: opensearch
LAST DEPLOYED: Mon Sep 19 23:15:04 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Watch all cluster members come up.
  $ kubectl get pods --namespace=default -l app.kubernetes.io/component=opensearch-cluster-master -w
(⎈ |docker-desktop:default):opensearch$ helm upgrade opensearch .
Release "opensearch" has been upgraded. Happy Helming!
NAME: opensearch
LAST DEPLOYED: Mon Sep 19 23:15:44 2022
NAMESPACE: default
STATUS: deployed
REVISION: 2
TEST SUITE: None
NOTES:
Watch all cluster members come up.
  $ kubectl get pods --namespace=default -l app.kubernetes.io/component=opensearch-cluster-master -w
(⎈ |docker-desktop:default):opensearch$ helm list
NAME      	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART           	APP VERSION
opensearch	default  	2       	2022-09-19 23:15:44.002241 +0300 IDT	deployed	opensearch-2.6.1	2.3.0

2022-09-19 20:30 UTC, prudhvigodithi commented
Hey @bkomraz1 thanks, I wanted to get a check with your change in place and if helm upgrade works with no issues. In general any chart changes should not break the helm upgrade as well, probably its good to add a CI test @peterzhuamazon @DandyDeveloper @TheAlgo @bbarani thoughts ?
Thank you

2022-09-19 20:32 UTC, prudhvigodithi commented
Hey @bkomraz1 I now see closely you have done upgrade from the local folder with your changes.

2022-09-19 20:33 UTC, prudhvigodithi approved these changes

2022-09-19 20:38 UTC, merged

2022-09-19 20:39 UTC, prudhvigodithi commented
@bkomraz1 can you please backport the change to `1.x` branch as well?

2022-09-20 15:03 UTC, prudhvigodithi commented
I have created a backport PR https://github.com/opensearch-project/helm-charts/pull/331