version bump to 1.3.9
opensearch-project/helm-charts pull request #403
Opened 2023-03-16 23:28 UTC by jordarlu

### Description
version bump to 1.3.9
 
### Issues Resolved
post task for release 1.3.9
 
### Check List
- [ ] Commits are signed per the DCO using --signoff

For any changes to files within Helm chart directories:
- [ ] Helm chart version bumped
- [ ] Helm chart `CHANGELOG.md` updated to reflect change

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/helm-charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-03-17 00:56 UTC, prudhvigodithi approved these changes

2023-03-18 15:26 UTC, TheAlgo requested changes
@jordarlu Can you please attach an issue to this PR?

2023-03-19 00:12 UTC, prudhvigodithi commented
Hey @TheAlgo thanks I have updated the description, please check.

2023-03-20 17:01 UTC, gaiksaya commented on charts/opensearch-dashboards/CHANGELOG.md
>  [Unreleased]: https://github.com/opensearch-project/helm-charts/compare/opensearch-dashboards-1.11.0...HEAD
Should be 1.12.0...HEAD

2023-03-20 17:13 UTC, jordarlu commented on charts/opensearch/CHANGELOG.md
>  [Unreleased]: https://github.com/opensearch-project/helm-charts/compare/opensearch-1.18.0...HEAD
Thanks for the correction on where I miseed ... updating it now @gaiksaya and @prudhvigodithi ... thanks!

2023-03-20 18:25 UTC, gaiksaya commented on charts/opensearch/CHANGELOG.md
>  [Unreleased]: https://github.com/opensearch-project/helm-charts/compare/opensearch-1.18.0...HEAD
Missed this one.

2023-03-20 18:33 UTC, jordarlu commented on charts/opensearch/CHANGELOG.md
>  [Unreleased]: https://github.com/opensearch-project/helm-charts/compare/opensearch-1.18.0...HEAD
:( I did miss this one ...

2023-03-20 23:21 UTC, gaiksaya approved these changes

2023-03-20 23:22 UTC, gaiksaya commented
Please rebase to 1 commit @jordarlu Thanks!

2023-03-23 15:48 UTC, prudhvigodithi commented
Hey @TheAlgo can you please check this PR again, Not able to merge as it as `requested changes` from you.
Thank you

2023-03-23 17:22 UTC, peterzhuamazon approved these changes

2023-03-23 19:34 UTC, merged