Remove hard coded opensearch.yml
opensearch-project/helm-charts pull request #504
Opened 2023-12-07 16:47 UTC by derek-ho

### Description
[Describe what this change achieves.]
 
### Issues Resolved
[List any issues this PR will resolve. You should likely open an issue if one does not already exist.]
 
### Check List
- [ ] Commits are signed per the DCO using --signoff

For any changes to files within Helm chart directories:
- [ ] Helm chart version bumped
- [ ] Helm chart `CHANGELOG.md` updated to reflect change

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/helm-charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-12-07 16:48 UTC, derek-ho commented on charts/opensearch/values.yaml
> -    plugins:
This file should be generated via the demo configuration script, if it is hard coded we will need to maintain this in two places.

2024-01-13 07:05 UTC, TheAlgo reviewed
But this sample yaml is very helpful for anyone starting opensearch right?

2024-01-13 14:59 UTC, smlx commented
I don't understand this change. This is a helm chart, they are configured via values files.. how are you generating your configuration otherwise?

2024-01-18 16:09 UTC, DarshitChanpura commented
@smlx @TheAlgo When an OpenSearch image is a downloaded and cluster is spun up, the Security plugin runs install demo configuration by default as part of install. During this phase, opensearch.yml is loaded with security related values. Hence we do not need to hardcode opensearch.yml. Feel free to experiment and lmk if otherwise.

2024-01-26 22:45 UTC, peterzhuamazon requested changes

2024-01-26 22:45 UTC, peterzhuamazon commented on charts/opensearch/CHANGELOG.md
> +## [2.17.3]
Use 2.18.1 as I put #503 as #2.18.0.

2024-01-26 22:45 UTC, peterzhuamazon commented on charts/opensearch/Chart.yaml
> +version: 2.17.3
2.18.1

2024-01-26 22:45 UTC, peterzhuamazon commented on charts/opensearch/CHANGELOG.md
> +- Removed hard coded opensearch.yml
This is a breaking change, please be clear in the changelog.

2024-01-29 20:19 UTC, peterzhuamazon approved these changes

2024-01-31 15:06 UTC, DarshitChanpura commented
@prudhvigodithi Could you please review this?

2024-02-06 15:39 UTC, DarshitChanpura commented
@prudhvigodithi Could you please add 1 more review?

2024-02-06 23:41 UTC, prudhvigodithi commented
Hey Just tested this and works fine with removing the `.Values.config` , basically when user adds the `opensearch.yml` through `.Values.config`, it gets added to `/usr/share/opensearch/config/opensearch.yml` overriding the default. Also one advantage is next if there is any change in  `opensearch.yml` and added through `.Values.config`, the pods get auto restarted and loads the new values from `opensearch.yml`.  So @DarshitChanpura and @derek-ho any specific reason we are removing, we can leave it as well right ?

2024-02-07 01:31 UTC, DarshitChanpura commented
> So @DarshitChanpura and @derek-ho any specific reason we are removing, we can leave it as well right ?

From what I understand, the opensearch.yml always gets created when demo configuration script is run (which is default). If in case the user decides to pass in custom configuration, they can always pass it in via .values.yml. In either of these two cases, the hardcoded opensearch.yml serves no purpose. Which is why we are removing this? @derek-ho Please add if I missed anything here.

2024-02-07 02:56 UTC, smlx commented
I don't know if it is on the roadmap of the Opensearch image to avoid generating the demo config at runtime but IMO it should be. Generating config at runtime has the following consequences for docker and k8s:

* it slows down container startup
* root filesystem can't be read only
* can't run the container as an arbitrary user (has to have permissions to write the config file)

IMO it makes more sense to aim for immutable images with defined injection points for configuration rather than generating config at runtime. Therefore I think this PR is a move in the wrong direction.

2024-02-07 03:56 UTC, prudhvigodithi commented
Instead of commenting out `opensearch.yml`, I have raised a PR https://github.com/opensearch-project/helm-charts/pull/516, that address configMap Read-only file system error when passed via `.Values.config`, with this the user can either use the default `opensearch.yml` or pass the `opensearch.yml` via `.Values.config`. The file will be created as `-rw-r--r-- 1 opensearch opensearch 3646 Feb  7 03:22 opensearch.yml`, having RW access within the cluster,  please check.

@TheAlgo @DarshitChanpura @peterzhuamazon @bbarani @derek-ho @smlx

2024-02-07 17:06 UTC, derek-ho commented
I can close this out, since I tested out the alternative also works and it seems the direction of the community is not towards removing this.

2024-02-07 17:06 UTC, closed without merging

2024-02-07 18:16 UTC, DarshitChanpura commented
This can be closed out since the changes in #516 addresses the read-only issue when writing demo configuration.